### ISSUE TITLE
VFG schema generator

### ISSUE THREAD

**Issue by PeterC66** [vue-generators/vue-form-generator#569] opened 2018-12-20 10:02 UTC
I'm submitting a feature request, or maybe a suggestion for development.

VFG expects a schema (and model) to specify a form. I would like to have **a VFG schema generator** (a standard VFG form) that enables me and my users to generate schemas (and their corresponding models). It need for now generate only the most commonly used fields.

I am interested in other's ideas, and whether anyone has worked on it already. I plan to work on this myself, if no-one has done it.

**Comment by DelfsEngineering** [comment] 2018-12-20 13:41
Do you mean something like this [https://github.com/vue-generators/vue-form-generator/issues/503](https://github.com/vue-generators/vue-form-generator/issues/503)

**Comment by PeterC66** [comment] 2018-12-20 14:01
I had read #503 but I had not envisaged a drag and drop aspect. Now I see that it could be relevant, and will add my interest to it.

My use case is users providing simple csv data files, and them defining (and saving) a form for editing and adding to each one of them.

**Comment by zoul0813** [comment] 2018-12-20 14:02
Duplicate of #503

**Closed by zoul0813** 2018-12-20 14:02 UTC
