### ISSUE TITLE
Property or method "debouncedValidate" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by gezichenshan** [vue-generators/vue-form-generator#345] opened 2017-11-14 12:27 UTC
I've created a custom field for postcode. but I got error in console."Property or method "debouncedValidate" is not defined on the instance but referenced during render "
```
<template>
  <input
      class="form-control"
      type="tel"
      v-model="value"
      :disabled="disabled"
      :maxlength="schema.maxlength"
      :placeholder="schema.placeholder"
      :readonly="schema.readonly"
      :formmethod="schema.formmethod"
      :debouncedValidate="schema.validator"
      @input="onEnter($event)"
      >
</template>

<script>
  import { abstractField } from "vue-form-generator";
  import { getConfig } from '../utils/api'
  export default {
    mixins: [ abstractField ],
    methods: {
      onEnter(event){
        this.value = this.value.replace(/[^0-9-]+/,'')
      }
    }
  };
</script>

```
something i missed?

**Comment by zoul0813** [comment] 2017-11-14 15:26
You didn't define it.  It's not a property defined in abstractField, it's part of the computed value.

When adding your custom field to the form, just provide a `validateDebounceTime` value in the field schema and it will create a debounce() function and call it for you.

Take a look at `src/fields/core/fieldInput.vue` for an example of a basic `input[type=text]` field.

Looks like you're trying to mask the input entered, which can be done using the `formatValueToField` and `formatValueToModel` methods, in a similar fashion to how `src/fields/core/fieldInput.vue` handles dates. You should remove the `@input`, and include the custom logic in the `formatValueTo*` methods.

**Comment by gezichenshan** [comment] 2017-11-15 14:05
I'll take a look on it. thank you!

**Comment by gezichenshan** [comment] 2017-11-15 16:12
I rewrite my custom filed in the following way with some console.log() to test. 
but I still caught the same error.I did something wrong?
```
<template>
  <input
      class="form-control"
      :id="getFieldID(schema)"
  		:type="schema.inputType"
  		:value="value"
  		@input="value = $event.target.value"
  		:class="schema.fieldClasses"
  		@change="schema.onChange || null"
  		:disabled="disabled"
  		:accept="schema.accept"
  		:alt="schema.alt"
  		:autocomplete="schema.autocomplete"
  		:checked="schema.checked"
  		:dirname="schema.dirname"
  		:formaction="schema.formaction"
  		:formenctype="schema.formenctype"
  		:formmethod="schema.formmethod"
  		:formnovalidate="schema.formnovalidate"
  		:formtarget="schema.formtarget"
  		:height="schema.height"
  		:list="schema.list"
  		:max="schema.max"
  		:maxlength="schema.maxlength"
  		:min="schema.min"
  		:minlength="schema.minlength"
  		:multiple="schema.multiple"
  		:name="schema.inputName"
  		:pattern="schema.pattern"
  		:placeholder="schema.placeholder"
  		:readonly="schema.readonly"
  		:required="schema.required"
  		:size="schema.size"
  		:src="schema.src"
  		:step="schema.step"
  		:width="schema.width"
  		:files="schema.files"
      >
</template>

<script>
  import { abstractField } from "vue-form-generator";
  import { getConfig } from '../utils/api'
  export default {
    mixins: [ abstractField ],
    methods: {
      // onEnter(event){
      //   this.value = this.value.replace(/[^0-9-]+/,'')
      // }
      formatValueToField(value) {
        // return '22222'
  			if (value != null) {
          console.log(77777)
  				// let dt;
  				// switch (this.schema.inputType) {
  				// 	case "date":
  				// 		dt = this.schema.format ? fecha.parse(value, this.schema.format) : new Date(value);
  				// 		return fecha.format(dt, "YYYY-MM-DD");
  				// 	case "datetime":
  				// 		dt = this.schema.format ? fecha.parse(value, this.schema.format) : new Date(value);
  				// 		return fecha.format(dt, "YYYY-MM-DD HH:mm:ss");
  				// 	case "datetime-local":
  				// 		dt = this.schema.format ? fecha.parse(value, this.schema.format) : new Date(value);
  				// 		return fecha.format(dt, "YYYY-MM-DDTHH:mm:ss");
  				// }
  			}

  			return value;
  		},

  		formatValueToModel(value) {
        // return '22222'
  			if (value != null) {
          console.log(99999)
  				// let m;
  				// switch (this.schema.inputType) {
  				// 	case "date":
  				// 		m = fecha.parse(value, "YYYY-MM-DD");
  				// 		if (m !== false) {
  				// 			if (this.schema.format)
  				// 				value = fecha.format(m, this.schema.format);
  				// 			else
  				// 				value = m.valueOf();
  				// 		}
  				// 		break;
  				// 	case "datetime":
  				// 		m = fecha.parse(value, "YYYY-MM-DD HH:mm:ss");
  				// 		if (m !== false) {
  				// 			if (this.schema.format)
  				// 				value = fecha.format(m, this.schema.format);
  				// 			else
  				// 				value = m.valueOf();
  				// 		}
  				// 		break;
  				// 	case "datetime-local":
  				// 		m = fecha.parse(value, "YYYY-MM-DDTHH:mm:ss");
  				// 		if (m !== false) {
  				// 			if (this.schema.format)
  				// 				value = fecha.format(m, this.schema.format);
  				// 			else
  				// 				value = m.valueOf();
  				// 		}
  				// 		break;
  				// 	case "number":
  				// 		return Number(value);
  				// 	case "range":
  				// 		return Number(value);
  				// }
  			}

  			return value;
  		}
    }
  };
</script>
```

**Comment by zoul0813** [comment] 2017-11-15 16:26
Can you provide a JSFiddle of this? I copied your custom field to my project and used it, ... I got an error about the "getConfig" as `../utils/api` is the wrong path for a custom field (assuming you put the field in your project, and not in the `node_modules/vue-form-generator/src/fields` folder.  `getConfig` isn't being used, so I just removed it ... after that, your custom field showed up in my form and output "99999" to my console with no warnings/errors.

**Comment by gezichenshan** [comment] 2017-11-23 03:29
here is the jsfiddle:https://jsfiddle.net/egfkqt7a/
I found that if I wrote the custom field in this way:
```
Vue.component("field-postcode", {
    template: '<input class="form-control" :id="getFieldID(schema)" :type="schema.inputType" :value="value" @input="value = $event.target.value" :class="schema.fieldClasses" @change="schema.onChange || null" :disabled="disabled" :accept="schema.accept" :alt="schema.alt" :autocomplete="schema.autocomplete" :checked="schema.checked" :dirname="schema.dirname" :formaction="schema.formaction" :formenctype="schema.formenctype" :formmethod="schema.formmethod" :formnovalidate="schema.formnovalidate" :formtarget="schema.formtarget" :height="schema.height" :list="schema.list" :max="schema.max" :maxlength="schema.maxlength" :min="schema.min" :minlength="schema.minlength" :multiple="schema.multiple" :name="schema.inputName" :pattern="schema.pattern" :placeholder="schema.placeholder" :readonly="schema.readonly" :required="schema.required" :size="schema.size" :src="schema.src" :step="schema.step" :width="schema.width" :files="schema.files" />',
 mixins: [ VueFormGenerator.abstractField ],
 methods: {
 formatValueToField(value) {
  if (value != null) {
   console.log(77777)
  }
  return value;
 },

 formatValueToModel(value) {
  if (value != null) {
   console.log(99999)
  }

  return value;
 }
}
```

**Comment by zoul0813** [comment] 2017-11-27 15:42
@gezichenshan how do I reproduce the error using your Fiddle? When I enter values into your Postcode field all I get is 99999 and 77777 output to the console depending on the input.  No errors about debounceValidate.

**Comment by gezichenshan** [comment] 2017-11-28 09:16
@zoul0813 Yes , in Fiddle there is no errors. I've explained in my last comment that if I use the Postcode field by importing it from another file, the errors will show.

**Comment by zoul0813** [comment] 2017-11-28 14:25
@gezichenshan I copied everything over to a local project, and imported the "fieldPostcode.vue" file and am still unable to reproduce the issue you're reporting.  Without a JSFiddle/Plunker showing the error or a git repo that can be cloned and tested ... I can't help you.

Are you using the latest version of VFG (2.1.1) ?

**Comment by gezichenshan** [comment] 2017-11-30 04:20
- 

- [ ]

**Comment by zoul0813** [comment] 2017-11-30 14:32
I'm still not able to reproduce the error.  However, you're Reg1.vue file is incomplete and I had to make some assumptions about how you declared the <vue-form-generator /> ... 

I went with ... 

```
<vue-form-generator :schema="schema" :model="model"></vue-form-generator>
```

You shouldn't be getting errors about `debouncedValidate` unless you're trying to use the debounce validation ... the code that calls 'debouncedValidate' is located in abstractField's computed setter for 'value'.

```
/// VFG debouncedValidate logic
if (this.$parent.formOptions && this.$parent.formOptions.validateAfterChanged === true) {
    if (this.$parent.formOptions.validateDebounceTime > 0) {
        if (!this.debouncedValidate)
            this.debouncedValidate = debounce(this.validate.bind(this), this.$parent.formOptions.validateDebounceTime);

        this.debouncedValidate();
    } else {
        this.validate();
    }
}
```

Even when I pass a formOptions object as `{ validateAfterChanged: true, validateDebounceTime: 5000 }` I still don't get an error ... unfortunately, without having an actual project that reproduces the error I can't help.  I'm going to close this issue for now, feel free to re-open it later if you can provide a complete project (something I can clone from github, or a JSFiddle/Plunker) that reproduces the reported error.

**Comment by gezichenshan** [comment] 2017-12-05 03:24
@zoul0813 Hi, I created a project on github to reproduce the error. You may check it out if it is convenient for you.
here it is: https://github.com/gezichenshan/vfg-custom-postalcode-field-demo :)

**Comment by zoul0813** [comment] 2017-12-05 15:36
I can reproduce the error in your project, ... taking a look at it now.

**Comment by zoul0813** [comment] 2017-12-05 16:07
Ok, I think I've tracked the issue down ... it looks like the older version of Vue that VFG was originally written against supported adding methods to the Vue components dynamically.  However, the newer version of Vue is throwing errors because "debouncedValidate" is not defined in the component, as it was being attached only in certain situations.  This seems to only occur if you're using a newer version of Vue than VFG was intended for.  

Working on a fix now.

**Closed** 2017-12-05 21:10 UTC
Labels: bug, difficulty: easy

**Comment by gezichenshan** [comment] 2017-12-06 09:10
@zoul0813 Thank you very much!
