### ISSUE TITLE
visible 

### ISSUE THREAD

**Issue by serverfire** [vue-generators/vue-form-generator#453] opened 2018-05-22 07:54 UTC
Hi.
When i set visibility of a field to false it will hide in my admin page and i cant edit it again. How can i set visibility to false only for user page not admin page.
I've attached a screenshot of my project.
![vue-form-generator](https://user-images.githubusercontent.com/132761/40348706-ada7d6b4-5db9-11e8-8c15-afd79ee2e903.PNG)

**Comment by zoul0813** [comment] 2018-05-22 17:08
You would have to change the value of the visibility based on what page you are currently viewing.

This is not a bug report, and appears to be a support request specific to your project and not to VFG.

I'm closing this issue.

**Closed by zoul0813** 2018-05-22 17:08 UTC
