### ISSUE TITLE
$emit events on user input

### ISSUE THREAD

**Issue by networkimprov** [vue-generators/vue-form-generator#426] opened 2018-03-22 08:01 UTC
**Feature Request**

In order to respond to user input actions, currently you have to set a watch function on the model. However this also catches programmatic model updates, and can't discern whether the update was by user action or the program.

VFG should $emit an 'input' event on any user input; no arguments are required, although it would be nice to get an argument giving the field name in the model that changed.

This is helpful when a server provides form input updates asynchronously.

**Comment by zoul0813** [comment] 2018-04-22 15:12
Can you not use the `model-updated` event?

```
<vue-form-generator ... @model-updated="onModelUpdated" />
```
onModelUpdated(model, schema) {
  // model and schema of update
},
```

**Comment by networkimprov** [comment] 2018-04-22 22:11
I believe 'model-updated' is emitted for any model change, not solely user input in the form? If so, it has the same limitation as a watch function on the model, described above.

Also I don't see any events documented in https://icebob.gitbooks.io/vueformgenerator/content/

**Comment by zoul0813** [comment] 2018-04-22 23:48
Model updated is called by VFG whenever it processes user input, fairly sure it’s not called by reactive updates.  Though, you could test this.

I’m also not sure how an input event being fired helps with server related updates?

**Comment by networkimprov** [comment] 2018-04-23 00:44
A quick test seems to confirm that @model-updated is emitted solely on user input. Now you just need to document that! :-)

One may need to take different actions for updates to the model pushed from a server vs input by user; e.g. inform the user that the form has changed. Hence my req for an input-only event.

**Comment by zoul0813** [comment] 2018-04-23 01:25
As the developer, shouldn’t you know the update was caused by the server response ... allowing you to have the opposite of what you’re looking for, negating the request and solving the issue?

As for documentation, this is an actively growing project and the source is available... that’s how I found the model updated.  If you have the time, we’d welcome any contributions you could make to he documentation.

Thanks.  I’m going to close this issue now as it appears resolved.

**Closed by zoul0813** 2018-04-23 01:25 UTC
Labels: need more information, question

**Comment by networkimprov** [comment] 2018-04-29 19:26
I suggest re-opening this issue until the documentation is rev'd for @model-updated.

Do the docs need a new page for events, and if not which page would they belong to?

I'll try to submit a patch when I have time, but that will be months from now. If I were in your shoes I'd update the docs ASAP so I wouldn't have to answer this Q again :-)
