### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by walkmanvova** [vue-generators/vue-form-generator#642] opened 2019-09-03 17:09 UTC
here:
https://vue-generators.gitbook.io/vue-generators/fields/custom_fields
this line: import { abstractField } from "VueFormGenerator";
works with this fix: import { abstractField } from "vue-form-generator";

**Comment by vuchl** [comment] 2019-10-23 10:01
Fixed in https://github.com/vue-generators/vue-form-generator-docs/pull/25

**Comment by zoul0813** [comment] 2019-10-23 12:56
Your example line doesn’t match the doc PR change ... 

Does this change also need to be reflected in this Repo?

**Comment by vuchl** [comment] 2019-10-24 13:20
I don't quite follow. Maybe it's the fact that the issue is listed here instead of the docs repo. I just wanted to update the issue here

**Comment by walkmanvova** [comment] 2019-10-24 13:24
Yes. Docs
--
Отправлено из Mail.ru для Android Четверг, 24 Октября 2019г., 16:20 +03:00 от Sebastian  notifications@github.com :

**Comment by zoul0813** [comment] 2019-10-24 17:36
Closing, this appears to be a duplicate of https://github.com/vue-generators/vue-form-generator-docs/pull/25

**Closed as completed by zoul0813** 2019-10-24 17:36 UTC
