### ISSUE TITLE
Validation does not work. Always show errors.

### ISSUE THREAD

**Issue by johnzuk** [vue-generators/vue-form-generator#399] opened 2018-02-28 22:09 UTC
Hi, I have problem with validation, in my case validation does not work. I created example:
https://jsfiddle.net/0mg1v81e/1464/
In this case validation alway show "This field is required!" error even if field is not empty. 
After empty field and set new value the number of errors is increasing in error array. You can see this in example above

**Comment by tomdickie** [comment] 2018-07-19 13:44
Take your form schema out of a method and put it in data or use a pojo for it.

Working version: https://jsfiddle.net/0mg1v81e/3937/

**Comment by zoul0813** [comment] 2018-12-10 21:20
@johnzuk I believe @tomdickie's solution resolves this, closing the issue.  Please reopen if the issue is unresolved by this.

**Closed by zoul0813** 2018-12-10 21:20 UTC
