### ISSUE TITLE
@2.3.1 input fields do not display text.

### ISSUE THREAD

**Issue by tizl1234** [vue-generators/vue-form-generator#511] opened 2018-10-10 16:40 UTC
Hi,
* **I'm submitting a ...**
  * [x] bug report
  * [ ] feature request
  * [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
VFG@2.3.1 Some input fields do not display text or any other data type ( first three in the example below), but the data changes in JSON.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  [codesandbox](https://codesandbox.io/s/m5zr4j88)
with pretty JSON output:
[fiddle](https://jsfiddle.net/tizl1234/8vwcy23b/3/)

* **What is the expected behavior?**
VFG@2.3.1 all input fieldes shows data.
- **What is the motivation / use case for changing the behavior?**
I suppose it's happening, because of the dot (.) or/and brackets ([]) operator in `model` property in ` schema` (e.g. `model:" mainBroker.url "`)
* **Please tell us about your environment:**

  * Version: [ 2.3.1]
  * Browser: [ Chrome 69.0.3497.100 ]
  * Language: [ES6/7]

I'm quite new in Vue.js and I hope I use VFG in proper way and I don't repeat already existed issue report.
You can change VFG version from 2.3.1 to 2.2.2. in codesandbox or jsfiddle and see the difference.

**Comment by qkdreyer** [comment] 2018-10-17 15:19
This looks like a major breaking change to me.

v2.3.1 : broken (https://jsfiddle.net/8cxh1nyg/1)
v2.3.0 : working (https://jsfiddle.net/8cxh1nyg/2)

**Comment by qkdreyer** [comment] 2018-10-17 15:21
@lionel-bijaoui Could this be caused by lodash-webpack-plugin ? (https://github.com/vue-generators/vue-form-generator/compare/v2.3.0...v2.3.1)

**Comment by zoul0813** [comment] 2018-11-02 14:40
should be fixed in 2.3.2

**Closed by zoul0813** 2018-11-02 14:40 UTC
Labels: bug
