### ISSUE TITLE
does not work with vue cli v3

### ISSUE THREAD

**Issue by nigel-dewar** [vue-generators/vue-form-generator#483] opened 2018-08-27 05:06 UTC
Hi There, Im new to vue so likely the error is at my end.

You are likely already aware of this but just mentioning in case there was some easy fix

I tried installing vue-form-generator in a new vue cli c3 project but to no avail.

It doesnt work and console complains of weird issues where it cant access 'vue' and vue.use doesnt work.
![image](https://user-images.githubusercontent.com/9402456/44641809-43493200-aa0c-11e8-80bf-de73c276e190.png)

Kind Regards

Nigel Dewar

**Comment by genu** [comment] 2018-09-01 15:17
Works fine for me, can you post some code?

**Comment by zoul0813** [comment] 2018-09-12 13:40
Can you provide sample code and steps to reproduce?

**Comment by ChadTaljaardt** [comment] 2018-09-12 14:41
Works for me and im running Vue cli3

**Comment by zoul0813** [comment] 2018-10-04 16:11
closing - @nigel-dewar if you can provide some sample code that reproduces this issue, please feel free to reopen the issue.

**Closed by zoul0813** 2018-10-04 16:11 UTC
Labels: need investigate, need more information, need repro fiddle
